# fly.toml app configuration file generated for cool-haze-5796 on 2023-07-18T16:53:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-haze-5796"
primary_region = "nrt"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
